baseurl = "http://tatamo.81.la/blog/"
languageCode = "ja"
title = "わたしろぐ"
canonifyurls = true

[permalinks]
post = "/:year/:month/:day/:filename/"
[params]
author = "Tatamo"
subtitle = "私録"
description = "Tatamo's weblog"
twitter_url = "https://twitter.com/__tatamo__"
github_url = "https://github.com/tatamo"
copyright_since = "2015"
copyright_latest = "2015"
