baseurl = "https://settlecode.com/"
languageCode = "en"
title = "Settle Code"
canonifyurls = true

[permalinks]
post = "/:filename"
[params]
author = "settle code"
subtitle = "Settle Code"
description = "settle's weblog"
twitter_url = "https://twitter.com/settlecode"
github_url = "https://github.com/settlecode"
copyright_since = "2019"
copyright_latest = "2020"


[menu]
	[[menu.main]]
		identifier = "about"
		name = "about"
		url = "/about/"
